brace_style = "PreferSameLine"
format_macro_matchers = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
match_arm_blocks = false
max_width = 190
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
short_array_element_width_threshold = 20
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
