[advisories]
ignore = []
notice = "deny"
unmaintained = "warn"
unsound = "deny"
vulnerability = "deny"
yanked = "deny"

[bans]
deny = []
multiple-versions = "warn"
skip = []
skip-tree = []
wildcards = "allow"

[licenses]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    "BlueOak-1.0.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "Unlicense",
]
allow-osi-fsf-free = "neither"
confidence-threshold = 0.925
copyleft = "deny"
exceptions = []
unlicensed = "deny"

[licenses.private]
ignore = true

[sources]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = ["valeratrades"]

[[targets]]
triple = "aarch64-unknown-linux-gnu"

[[targets]]
triple = "x86_64-unknown-linux-gnu"

[[targets]]
triple = "x86_64-unknown-linux-musl"
