alias tm="todo manual"
alias teva="todo manual ev -a"
alias tevs="todo manual ev -s"
alias tdo="cs ${HOME}/.data/personal/"
alias tstart="todo timer start"
alias tdone="todo timer done"
alias tfailed="todo timer failed"
