jobs:
  tokei:
    name: Reasonable Amount of Comments
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Installation
      uses: taiki-e/install-action@v2
      with:
        tool: tokei
    - name: Generate Tokei output
      run: tokei -o json > tokei_output.json
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Check Rust comments
      run: "\t\t\t\t comments=$(jq '.Rust.comments' tokei_output.json)\n\t\t\t\t code=$(jq\
        \ '.Rust.code' tokei_output.json)\n\t\t\t\t if [ $((comments * 10)) -ge $code\
        \ ]; then\n\t\t\t\t\t echo \"Number of comments should be less than 10% of\
        \ code\"\n\t\t\t\t\t exit 1\n\t\t\t\t else\n\t\t\t\t\t echo \"Check passed:\
        \ Number of comments is less than 10% of code\"\n\t\t\t\t fi\n\t\t\t\t"
name: CI
'on':
  pull_request: {}
  push: {}
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch: {}
permissions:
  contents: read
