jobs:
  clippy:
    if: github.event_name != 'pull_request'
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@clippy
    - run: cargo clippy --tests -- -Dwarnings
    timeout-minutes: 45
  doc:
    env:
      RUSTDOCFLAGS: -Dwarnings
    if: needs.pre_ci.outputs.continue
    name: Documentation
    needs: pre_ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - uses: dtolnay/install@cargo-docs-rs
    - run: cargo docs-rs
    timeout-minutes: 45
  machete:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-machete
    - name: Cargo Machete
      run: "\t\t\t\t\t\tcargo machete\n\t\t\t\t\t\texit_code=$?\n\t\t\t\t\t\tif [\
        \ $exit_code = 0 ]; then\n\t\t\t\t\t\t\techo \"Found unused dependencies\"\
        \n\t\t\t\t\t\t\texit $exit_code\n\t\t\t\t\t\tfi\n\t\t\t"
  miri:
    if: needs.pre_ci.outputs.continue
    name: Miri
    needs: pre_ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@miri
    - run: cargo miri setup
    - env:
        MIRIFLAGS: -Zmiri-strict-provenance
      run: cargo miri test
    timeout-minutes: 45
  sort:
    name: Cargo Sorted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installation
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-sort
    - name: Check if Cargo.toml is sorted
      run: "cargo sort -wc\nexit_code=$?\nif [ $exit_code != 0 ]; then\n  echo \"\
        Cargo.toml is not sorted. Run \\`cargo sort -w\\` to fix it.\"\n  exit $exit_code\n\
        fi\n"
  tests:
    if: needs.pre_ci.outputs.continue
    name: Rust ${{matrix.rust}}
    needs: pre_ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - if: github.ref == 'refs/heads/release'
      name: Set RUSTFLAGS for release branch
      run: echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
    - if: matrix.rust == 'nightly'
      name: Enable type layout randomization
      run: echo RUSTFLAGS=${RUSTFLAGS}\ -Zrandomize-layout\ --cfg=exhaustive >> $GITHUB_ENV
    - run: cargo update
    - run: cargo check
    - run: cargo test
    strategy:
      fail-fast: false
      matrix:
        rust:
        - nightly
        - stable
    timeout-minutes: 45
  tokei:
    name: Reasonable Amount of Comments
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Installation
      uses: taiki-e/install-action@v2
      with:
        tool: tokei
    - name: Generate Tokei output
      run: tokei -o json > tokei_output.json
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Check Rust comments
      run: "\t\t\t\t\t\tcomments=$(jq '.Rust.comments' tokei_output.json)\n\t\t\t\t\
        \t\tcode=$(jq '.Rust.code' tokei_output.json)\n\t\t\t\t\t\tif [ $((comments\
        \ * 10)) -ge $code ]; then\n\t\t\t\t\t\t\techo \"Number of comments should\
        \ be less than 10% of code\"\n\t\t\t\t\t\t\texit 1\n\t\t\t\t\t\telse\n\t\t\
        \t\t\t\t\techo \"Check passed: Number of comments is less than 10% of code\"\
        \n\t\t\t\t\t\tfi\n\t\t\t"
'on':
  pull_request: {}
  push: {}
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch: {}
